services:
  amps:
    build:
      context: ./amps-docker
      dockerfile: Dockerfile
    ports:
      - "9007:9007" # WebSocket for React.js client
      - "9008:9008" # TCP for Python services
      - "8085:8085" # Admin interface
    volumes:
      - amps_logs:/var/log/amps
    networks:
      - demo-network

  jaeger:
    image: jaegertracing/all-in-one:1.52
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC (for OpenTelemetry traces)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - demo-network

  marker:
    build:
      context: ./marker
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # React dev server
    depends_on:
      - amps
      - jaeger
    environment:
      - NODE_ENV=development
    networks:
      - demo-network

  # processor:
  #   build: ./processor
  #   depends_on:
  #     - amps
  #     - jaeger
  #   environment:
  #     - AMPS_HOST=amps:9000
  #     - JAEGER_ENDPOINT=[invalid url, do not cite]

  # persister:
  #   build: ./persister
  #   depends_on:
  #     - amps
  #     - jaeger
  #   environment:
  #     - AMPS_HOST=amps:9000
  #     - JAEGER_ENDPOINT=[invalid url, do not cite]

volumes:
  amps_logs:

networks:
  demo-network:
    driver: bridge